import { Document } from "../document";

export const demoResources: Document[] = [
  {
    name: "my-lambda",
    awsService: "lambda",
    region: "us-east-1",
    description: "My Lambda Function",
    arn: "1",
  },
  {
    name: "graphql-handler",
    awsService: "lambda",
    region: "eu-central-1",
    arn: "2",
  },
  {
    name: "serverless-demo",
    awsService: "lambda",
    region: "ap-southeast-2",
    arn: "3",
  },
  {
    name: "this-is-eks-server-trust-me",
    awsService: "lambda",
    region: "us-west-2",
    arn: "4",
  },
  {
    name: "IHateCloudFormation",
    awsService: "lambda",
    region: "eu-west-3",
    arn: "5",
  },
  {
    name: "InfinitelyScalableEC2Instance-serverless",
    awsService: "lambda",
    region: "ca-central-1",
    arn: "6",
  },
  {
    name: "you-should-be-using-cloudash-already",
    awsService: "lambda",
    region: "ca-central-1",
    arn: "7",
  },
  {
    name: "dynamodb-stream-handler",
    awsService: "lambda",
    region: "sa-east-1",
    arn: "8",
  },
  {
    name: "the-best-serverless-database",
    awsService: "dynamodb",
    region: "sa-east-1",
    arn: "9",
  },
  {
    name: "iPromiseThisIsntMocked",
    awsService: "dynamodb",
    region: "us-east-1",
    arn: "10",
  },
  {
    name: "global-table-not-super-consistent",
    awsService: "dynamodb",
    region: "eu-east-1",
    arn: "11",
  },
  {
    name: "mongodb-is-webscale",
    awsService: "dynamodb",
    region: "us-west-1",
    arn: "12",
  },
  {
    name: "graphql-with-dynamodb-is-awsome",
    awsService: "dynamodb",
    region: "sa-east-1",
    arn: "13",
  },
  {
    name: "table-with-1000-items",
    awsService: "dynamodb",
    region: "sa-east-1",
    arn: "14",
  },
  {
    name: "im-bad-at-relations-serverless",
    awsService: "dynamodb",
    region: "eu-central-9000",
    arn: "15",
  },
  {
    name: "public-read-acl-is-the-way-to-go-dynobase",
    awsService: "s3",
    region: "us-east-1",
    arn: "16",
  },
  {
    name: "privateStuff!!!!!",
    awsService: "s3",
    region: "us-east-1",
    arn: "17",
  },
  {
    name: "bucket-i-forgot-to-secure",
    awsService: "s3",
    region: "us-east-1",
    arn: "18",
  },
  {
    name: "terraform-state",
    awsService: "s3",
    region: "us-east-1",
    arn: "19",
  },
  {
    name: "server-but-without-compute",
    awsService: "s3",
    region: "us-east-1",
    arn: "20",
  },
  {
    name: "logstash-for-dummies",
    awsService: "logs",
    region: "us-east-1",
    arn: "21",
  },
  {
    name: "i-hate-aws-cloudWatch-log-groups",
    awsService: "logs",
    region: "us-east-1",
    arn: "22",
  },
  {
    name: "logsForMyLambdas",
    awsService: "logs",
    region: "us-east-1",
    arn: "23",
  },
  {
    name: "ifYouAreReadingThisYouAreProbablySickOfAWSConsole",
    awsService: "logs",
    region: "us-east-1",
    arn: "24",
  },
  {
    name: "/aws/prod",
    awsService: "logs",
    region: "us-east-1",
    arn: "25",
  },
  {
    name: "/aws/api-gateway",
    awsService: "logs",
    region: "us-east-1",
    arn: "26",
  },
  {
    name: "nosqlworkbench-whatsthat",
    awsService: "logs",
    region: "us-east-1",
    arn: "27",
  },
  {
    name: "serverless-graphql-stack",
    awsService: "cloudformation",
    region: "us-east-1",
    arn: "28",
  },
  {
    name: "serverless-rest-api",
    awsService: "cloudformation",
    region: "eu-central-1",
    arn: "29",
  },
  {
    name: "dynobase-assets-licenses-website-etc",
    awsService: "cloudformation",
    region: "eu-central-1",
    arn: "30",
  },
  {
    name: "cdk-assets-bucket",
    awsService: "cloudformation",
    region: "eu-central-1",
    arn: "31",
  },
];
